export const bookCategories = [
  {
    id: 1000,
    key: 'all',
    name: 'Все книги',
    quantity: null,
  },
  {
    id: 0,
    key: 'business',
    name: 'Бизнес-книги',
    quantity: 14,
  },
  {
    id: 1,
    key: 'detectives',
    name: 'Детективы',
    quantity: 8,
  },
  {
    id: 2,
    key: 'childrens',
    name: 'Детские книги',
    quantity: 14,
  },
  {
    id: 3,
    key: 'foreign',
    name: 'Зарубежная литература',
    quantity: 2,
  },
  {
    id: 4,
    key: 'history',
    name: 'История',
    quantity: 5,
  },
  {
    id: 5,
    key: 'classical',
    name: 'Классическая литература',
    quantity: 12,
  },
  {
    id: 6,
    key: 'psychology',
    name: 'Книги по психологии',
    quantity: 11,
  },
  {
    id: 7,
    key: 'computer',
    name: 'Компьютерная литература',
    quantity: 54,
  },
  {
    id: 8,
    key: 'culture',
    name: 'Культура и искусство',
    quantity: 5,
  },
  {
    id: 9,
    key: 'science',
    name: 'Наука и образование',
    quantity: 2,
  },
  {
    id: 10,
    key: 'journalism',
    name: 'Публицистическая литература',
    quantity: 0,
  },
  {
    id: 11,
    key: 'reference',
    name: 'Справочники',
    quantity: 10,
  },
  {
    id: 12,
    key: 'fantasy',
    name: 'Фантастика',
    quantity: 12,
  },
  {
    id: 13,
    key: 'humor',
    name: 'Юмористическая литература',
    quantity: 8,
  },
];
